### ISSUE TITLE
git branch-stash command not found.

### ISSUE THREAD

**Issue by fuel-wlightning** [gitext-rs/git-stack#221]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/gitext-rs/git-stack/discussions)
- [X] I have searched the existing issues

### Description

After running git stack --pull if I want to undo it asks me to do a:
`git branch-stash pop git-stack`

When I try to run this command, git says:
`git: 'branch-stash' is not a git command. See 'git --help'.`

### Version

0.8.1

### Steps to reproduce

- On MacOS 12.3 (on Intel processor) install git via XCode Command Line Tools to get Apple git version git version 2.32.0 (Apple Git-132))
- install git-stack via `cargo install git-stack`
- Ensure `${HOME}/.cargo/bin` is in your path.
- ensure you have an existing branch based on a protected branch that has been updated in origin.
- `git stack --pull` - Which rebases the branch on the updated protected branch successfully.
- `git branch-stash pop git-stack` to attempt to undo the rebase.

### Actual Behaviour

`git: 'branch-stash' is not a git command. See 'git --help'.`

### Expected Behaviour

It would undo the latest rebases from the pull.

### Debug Output

```
% git -vv branch-stash pop git-stack
unknown option: -vv
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]
% 
```

**Comment by epage** [comment]
Yes,, this has now been split out into a separate repo / crate.  I still need to update the documentation to reflect that.

See https://github.com/gitext-rs/git-branch-stash

**Comment by fuel-wlightning** [comment]
Thank you! I fixed by doing `cargo install git-branch-stash-cli`
