### ISSUE TITLE
Provide a way to move up/down the stack

### ISSUE THREAD

**Issue by epage** [gitext-rs/git-stack#27]
### 

- [X] I have searched the [discussions](https://github.com/epage/git-stack/discussions)
- [X] I have searched the existing issues

### Version

0.1.0

### Use Case

Looking up my upstream and switching to it can be distracting.  Git finds shortcuts useful enough to have `git checkout -`.  Providing a way to move HEAD up/down will be a help

### Requirements

- Move up/down
- Moving down handles ambiguities

### Possible Solutions

`git switch-parent`
- Implies action through relation to `git switch` command
- "branch" is implied since switching is usually between branches
- `parent` is less ambiguous than `upstream`

`git switch-child`
- Accept which child on command-line
- Prompts when no child selected

### Alternative Solutions

- [`depot-tools`](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html) represents this with special git subcommands, `nav-downstream` and `nav-upstream`
  - Prompts the user on ambiguity

**Comment by epage** [comment]
Thanks for the inspiration!

In considering this feature, I'd also love to be able to use this in other commands, like `git diff HEAD<..HEAD`.  I wish git allowed plugging in additional syntax like that.  A not-very-ergonomic approach is to have a `--print` argument that says what the prev/next is.  Aliases can make it slightly more ergonomic.

**Comment by epage** [comment]
> You're probably aware, but for the specific case of getting parent commits, you can use HEAD~ or HEAD^ (https://git-scm.com/docs/gitrevisions). The git-revset command above is nice because it lets you also do children queries.

The difference is I'm not wanting to move by commit but by branch, regardless of how many commits are in it.

**Comment by searleser97** [comment]
> > You're probably aware, but for the specific case of getting parent commits, you can use HEAD~ or HEAD^ (https://git-scm.com/docs/gitrevisions). The git-revset command above is nice because it lets you also do children queries.
> 
> The difference is I'm not wanting to move by commit but by branch, regardless of how many commits are in it.

+1

**Comment by epage** [comment]
@searleser97 since you expressed interest in this, could you describe how you see yourself using a command like this and what you would need from it?

I'm looking to understand
- Requirements
- Level of importance (so far in my `git-stack` usage, I've not been moving up the stack as much as I'd expected)

**Comment by searleser97** [comment]
@epage I actually just found `graphite` which is just what I was looking for: https://github.com/screenplaydev/graphite-cli

and the ability to navigate up/down branches is documented here: https://docs.graphite.dev/guides/graphite-cli/navigating-a-stack#moving-up-and-down-a-stack

**Comment by epage** [comment]
Oh neat!  When I started `git-stack`,  I could find very few programs in this space and they seemed pretty esoteric.  Its amazing what you find after you start your own :).  I've now added this to our comparison document.

Would you be willing to share what is it about graphite that makes it what you are looking for so I can have more perspectives to be looking at this from?

**Comment by arxanas** [comment]
I implemented `git next --branch`/`git prev --branch` in git-branchless here: https://github.com/arxanas/git-branchless/pull/192

It might also be interesting because you can add the `--all` option to go to the first or last branch in a stack, or the `--interactive` option to select between ambiguous branches interactively.

**Comment by epage** [comment]
This was implemented in #257
