### ISSUE TITLE
git config stack.stack not taking effect

### ISSUE THREAD

**Issue by Bouke** [gitext-rs/git-stack#96]
### 

- [ ] I have searched the [discussions](https://github.com/epage/git-stack/discussions)
- [ ] I have searched the existing issues

### Description

I'm trying to change the default `--stack` argument to `descendants` to reduce the amount of output generated by `git stack`. I believe this should work, but I can't seem to get it to work:

```
$ git config stack.stack descendants

$ git config stack.stack descendants
descendants

$ git stack --dump-config -
[stack]
...
	stack=All
```

### Version

0.2.9

### Debug Output

```
[TRACE git_stack::config] Initializing
[TRACE git_stack::config] Loading gitconfig
[TRACE git_stack::config] Loading /Users/bouke/Developer/XXX/.gitconfig
[TRACE git_stack::config] Loading /Users/bouke/Developer/XXX/.git/config (< this file contains the stack.stack config)
```

**Comment by epage** [comment]
I just release v0.4.1 which includes #108

**Comment by Bouke** [comment]
Working great, thanks!
